# Comments
format_code_in_doc_comments = true
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Code
reorder_impl_items = true
