[package]
name = "acceptxmr"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
description = "Track Monero payments easily, efficiently and reliably."
repository = "https://github.com/busyboredom/acceptxmr"
readme = "README.md"
keywords = ["monero", "xmr"]
categories = ["cryptography::cryptocurrencies"]

[lib]
name = "acceptxmr"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
monero = { git = "https://github.com/busyboredom/monero-rs.git", branch = "check-with-checker" }
hex = "0.4"
log = "0.4"
sled = "0.34"
bincode = "1"
rand = "0.8"
rand_chacha = "0.3"
indexmap = "1"

[dev-dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.10"
actix-web-actors = "4.0.0-beta.7"
actix-files = "0.6.0-beta.8"
env_logger = "0.9"
bytestring = "1"
tempfile = "3"
httpmock = "0.6"
