[package]
name = "acceptxmr"
version = "0.11.0"
edition = "2021"
rust-version = "1.58"
license = "MIT OR Apache-2.0"
description = "Accept monero in your application."
repository = "https://github.com/busyboredom/acceptxmr"
readme = "README.md"
keywords = ["crypto", "gateway", "monero", "payment", "xmr"]
categories = ["cryptography::cryptocurrencies"]

[lib]
name = "acceptxmr"
path = "src/lib.rs"

[dependencies]
bincode = "2.0.0-rc"
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1", "http2", "tcp"] }
indexmap = "1"
log = "0.4"
monero = "0.17"
rand = "0.8"
rand_chacha = "0.3"
serde = {version = "1", features = ["derive"], optional = true }
serde_json = "1"
sled = "0.34"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
thiserror = "1"

[dev-dependencies]
actix = "0.13"
actix-files = "0.6"
actix-session = { version = "0.6", features = ["cookie-session"] }
actix-web = "4"
actix-web-actors = "4"
bytestring = "1"
env_logger = "0.9"
httpmock = "0.6"
serde = "1"
tempfile = "3"

[[example]]
name = "demo"
required-features = ["serde"]
