[package]
name = "acceptxmr"
version = "0.1.0"
edition = "2018"

[lib]
name = "acceptxmr"
path = "src/lib.rs"

[[bin]]
name = "acceptxmr_demo"
path = "src/bin/acceptxmr_demo.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0", features = ["json"] }
serde = "1"
serde_json = "1"
monero = "0"
hex = "0"
qrcode = "0"
env_logger = "0"
log = "0"
actix = "0.12"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
actix-files = "0.6.0-beta.6"
bytestring = "1"
sled = "0"
bincode = "1"
