# Needed because simply blanket allowing duplicate crates does not currently work in workspaces.
allowed-duplicate-crates = [
    "async-channel",
    "async-io",
    "async-lock",
    "axum-core",
    "axum",
    "bitflags",
    "event-listener-strategy",
    "event-listener",
    "fastrand",
    "futures-lite",
    "h2",
    "hashbrown",
    "http-body",
    "http",
    "hyper",
    "indexmap",
    "linux-raw-sys",
    "parking_lot_core",
    "parking_lot",
    "polling",
    "redox_syscall",
    "regex-automata",
    "regex-syntax",
    "rustix",
    "socket2",
    "strsim",
    "syn",
    "sync_wrapper",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "windows-sys",
    "windows-targets",
]