[package]
name = "acceptxmr"
version = "0.14.0"
edition = "2021"
rust-version = "1.76"
license = "MIT OR Apache-2.0"
description = "Accept monero in your application."
repository = "https://github.com/busyboredom/acceptxmr"
readme = "README.md"
keywords = ["crypto", "gateway", "monero", "payment", "xmr"]
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[lib]
name = "acceptxmr"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[dependencies]
backoff = { workspace = true, features = ["tokio"] }
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["std"] }
bytes.workspace = true
hex.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["client", "http1", "http2"] }
hyper-rustls = { workspace = true, features = ["logging", "http1", "http2", "tls12", "webpki-tokio", "webpki-roots", "ring"] }
hyper-util = { workspace = true, features = ["client-legacy", "http1", "http2"] }
indexmap.workspace = true
log.workspace = true
md-5.workspace = true
monero.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rayon.workspace = true
serde = { workspace = true, features = ["derive", "alloc"], optional = true }
serde_json.workspace = true
sled = { workspace = true, optional = true }
sqlite = { workspace = true, optional = true }
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "tracing"] }

[features]
bincode = ["dep:bincode"]
in-memory = []
serde = ["dep:serde"]
sled = ["bincode", "dep:sled"]
sqlite = ["bincode", "dep:sqlite"]

[dev-dependencies]
actix.workspace = true
actix-files.workspace = true
actix-session = { workspace = true, features = ["cookie-session"] }
actix-web.workspace = true
actix-web-actors.workspace = true
bytestring.workspace = true
env_logger.workspace = true
handlebars = { workspace = true, features = ["dir_source"] }
qrcode.workspace = true
serde.workspace = true
test-case.workspace = true
testing-utils.workspace = true
# This is a workaround to enable features in tests.
acceptxmr = { workspace = true, features = ["sled", "in-memory", "sqlite"] }

[[example]]
name = "custom_storage"

[[example]]
name = "nojs"
required-features = ["serde", "in-memory"]

[[example]]
name = "persistence"
required-features = ["sqlite"]

[[example]]
name = "websockets"
required-features = ["serde", "in-memory"]
