name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'
  RUSTDOCFLAGS: '-D warnings'
jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: rustfmt, clippy
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features
    - name: Doc
      run: cargo doc --all-features --all
  build:
    strategy:
      matrix:
        rust: [
          1.68.0,
          stable,
          nightly
        ]
        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - uses: Swatinem/rust-cache@v2.2.1
    - name: Build
      run: cargo build --verbose
    - name: Build with all features
      run: cargo build --verbose --all-features
  test:
    strategy:
      matrix:
        rust: [
          1.68.0,
          stable,
          nightly
        ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - uses: Swatinem/rust-cache@v2.2.1
    - run: cargo test --verbose --all-features
